### ISSUE TITLE
Getting an exception in demo.js when I use the following initial data

### ISSUE THREAD

**Issue by abrahamjatibm** [jscad/csg-viewer#33]
const initializeData = function () {
  // let a = cube({size: 100 * Math.random()});
   let a = cube({size:20})
  let b = sphere({radius: 9});
  return a.subtract(b).toPolygons();
}

state.js:21 error TypeError: Cannot read property 'Symbol(Symbol.iterator)' of undefined
    at flatten (utils.js:2)
    at entitiesFromSolids.js:32
    at Array.map (<anonymous>)
    at entitiesFromSolids (entitiesFromSolids.js:17)
    at setEntitiesFromSolids (dataParamsReducers.js:6)
    at state.js:16
    at ScanSink.event (accumulate.js:65)
    at MergeSink.event (merge.js:110)
    at IndexSink.event (IndexSink.js:28)
    at MapSink.event (Map.js:71)

**Comment by profOnno** [comment]
I think you want this:
```
const makeCsgViewer = require('../src/index')
const {cube,sphere} = require('@jscad/scad-api').primitives3d

const initializeData = function () {
//return cube({size: 100 * Math.random(), center:true})
  let a = cube({size:20, center: [1,1,0]})
  let b = sphere({r: (20+5)/2}).translate([0,0,20/2]);
  return a.subtract(b);//.toPolygons();
}
```
Don't forget to add the sphere to the require.

**Comment by z3dev** [comment]
Closing. Please reopen at OpenJSCAD.org
