### ISSUE TITLE
grid is not rendering when canvas 

### ISSUE THREAD

**Issue by peter-hartmann** [jscad/csg-viewer#35]
If instead of ```document.body```  a canvas element is specified, then the grid doesn't render.  All other functions seem to work fine.
 
    makeCsgViewer(document.querySelector('canvas'), ...

Any idea?

**Comment by z3dev** [comment]
@peter-hartmann please use the regl-render package found on OpenJSCAD.org

This package has been moved and improved as part of OpenJSCAD.org
